authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'  

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/candidate/', views.signup_candidate, name='signup_candidate'),
    path('signup/candidate/verify/', views.verify_email_candidate, name='verify_email_candidate'),
    path('verify/candidate/resend/', views.resend_code_candidate, name='resend_code_candidate'),
    path('signup/employer/', views.signup_employer, name='signup_employer'),
    path('signup/employer/verify/', views.verify_email_employer, name='verify_email_employer'),
    path('verify/employer/resend/', views.resend_code_employer, name='resend_code_employer'),
    path('login/', views.login, name='login'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('reset-password/verify/', views.reset_verify, name='reset_password_verify'),

]

candidate_profile/urls.py
from django.urls import path
from . import views

app_name = 'candidate_profile'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('save-job/', views.save_job, name='save_job'),
    path('saved-jobs/', views.saved_jobs, name='saved_jobs'),
    path('applications/', views.applied_jobs, name='applied_jobs'),
    path('applications/<int:application_id>/', views.application_detail, name='application_detail'),
    path('applications/interviews/', views.interview_list, name='interview_list'),
    path('upload_cv/', views.upload_and_review_cv, name='upload_cv'),
    path('clear-cv/', views.clear_cv, name='clear_cv'),
    path('profile/', views.profile_manage, name='profile_manage'),
    path('toggle-notify/', views.toggle_notify, name='toggle_notify'),
    path('profile/location/', views.update_location, name='update_location'),
    path('skill-gap/', views.skill_gap, name='skill_gap'),
    path('premium/recommendations/', views.premium_recommendations, name='premium_recommendations'),
    path('premium/', views.premium, name='premium'),
    path('premium/subscribe/', views.subscribe_premium, name='subscribe_premium'),
    path('logout/', views.logout, name='logout'),
    
]

templates/includes/footer.html
{% load static %}

<footer class="jobplugin__footer jobplugin__bg-dark jobplugin__footer-cta-spacer">
    <div class="jobplugin__container">
        <!-- Footer Four Columns -->
        <div class="jobplugin__row jobplugin__four-column" id="contact-list">
            <div class="jobplugin__column">
                <!-- Footer Column Head -->
                <div class="jobplugin__footer-head">
                    <h4 class="h5">For Clients</h4>
                    <span class="jobplugin__footer-head__seprator jobplugin__bg-primary"></span>
                </div>

                <!-- Footer Links -->
                <nav class="jobplugin__footer-links">
                    <ul>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">How to Hire</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Talent Marketplace</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Project Catalog</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Hire an Agency</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Enterprise</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Any Hire</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Contract-to-Hire</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="jobplugin__column">

                <!-- Footer Column Head -->
                <div class="jobplugin__footer-head">
                    <h4 class="h5">For Talent</h4>
                    <span class="jobplugin__footer-head__seprator jobplugin__bg-primary"></span>
                </div>
                <!-- Footer Links -->
                <nav class="jobplugin__footer-links">
                    <ul>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">How to Find Work</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Direct Contracts</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="jobplugin__column">
                <!-- Footer Column Head -->
                <div class="jobplugin__footer-head">
                    <h4 class="h5">Resources</h4>
                    <span class="jobplugin__footer-head__seprator jobplugin__bg-primary"></span>
                </div>
                <!-- Footer Links -->
                <nav class="jobplugin__footer-links">
                    <ul>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Help & Support</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Success Stories</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Resources</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Blog</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                {% comment %} <span class="jobplugin__footer-links__icon jobplugin__text-primary rj-icon rj-forward"></span> {% endcomment %}
                                <span class="jobplugin__footer-links__text">Community</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="jobplugin__column">
                <!-- Footer Column Head -->
                <div class="jobplugin__footer-head">
                    <h4 class="h5">Contact</h4>
                    <span class="jobplugin__footer-head__seprator jobplugin__bg-primary"></span>
                </div>
                <!-- Footer Links -->
                <nav class="jobplugin__footer-links">
                    <ul>
                        <li>
                            <a href="#">
                                <span class="jobplugin__footer-links__number">+977 9869358650</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="jobplugin__footer-links__text">workwise@gmail.com</span>
                            </a>
                        </li>
                        <li>
                            <address class="jobplugin__footer-links__address">Kathmandu, koteshowor</address>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- Footer Secondary -->
    <div class="jobplugin__footer-secondary">
        <div class="jobplugin__container">
            <!-- Footer Sublinks -->
            <ul class="jobplugin__footer-sublinks">
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- Footer Social Networks -->
            <ul class="jobplugin__social-networks">
            <li>
                <a class="hover:jobplugin__bg-primary hover:jobplugin__border-primary" href="#" aria-label="Facebook">
                <i class='bx bxl-facebook-square'></i>
                </a>
            </li>
            <li>
                <a class="hover:jobplugin__bg-primary hover:jobplugin__border-primary" href="#" aria-label="Instagram">
                <i class='bx bxl-instagram'></i>
                </a>
            </li>
            <li>
                <a class="hover:jobplugin__bg-primary hover:jobplugin__border-primary" href="#" aria-label="Twitter">
                <i class='bx bxl-twitter'></i>
                </a>
            </li>
            <li>
                <a class="hover:jobplugin__bg-primary hover:jobplugin__border-primary" href="#" aria-label="YouTube">
                <i class='bx bxl-youtube'></i>
                </a>
            </li>
            </ul>

            <!-- Footer Copyrights Text -->
            <p class="jobplugin__copyrights">© 2015 - 2023 WorkWise ®      All Rights Reserved.</p>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="jobplugin__header">
    <div class="jobplugin__container">
        <div class="jobplugin__header-holder">
            <div class="jobplugin__header-left">
                <!-- Logo of the Site -->
                <strong class="jobplugin__header-logo">
                    <a href="{% url 'index:home'%}">
                        <img src="{% static 'images/logo.svg' %}" alt="Workwise">
                    </a>
                </strong>
                
            </div>
            <div class="jobplugin__header-right">
                <div class="jobplugin__navigation">
                    <!-- Main Navigation Mobile Close -->
                    <button type="button" class="jobplugin__navigation-close">
                        <span class="jobplugin__bg-primary"></span>
                        <span class="jobplugin__bg-primary"></span>
                    </button>
                    <!-- Main Navigation -->
                    <nav class="jobplugin__nav">
                        <ul>
                            
                            <li>
                                <a href="#find-talent-section">Find Talent</a>
                                
                            </li>
                            <li>
                                <a href="{% url 'index:jobs_list'%}">Find Work</a>
                                
                            </li>
                            <li><a href="#">Blogs</a></li>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#contact-list">Contact</a></li>
                        </ul>
                    </nav>
                    <!-- Header Authentication Buttons -->
                    {% if request.session.employer_id %}
                    <div class="jobplugin__header-avatar" style="display: flex;align-items: center;padding: 0.5rem;">
                        {# TODO: once you have real images, swap out the dummy below #}
                        <a href="{% url 'employer:dashboard'%}"><img
                        src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
                        alt="User Avatar"
                        style="width: 36px;height: 36px;border-radius: 50%;object-fit: cover;"
                        class="avatar-circle"  ></a>
                    </div>
                    {% elif request.session.candidate_id  %}
                    <div class="jobplugin__header-avatar" style="display: flex;align-items: center;padding: 0.5rem;">
                        {# TODO: once you have real images, swap out the dummy below #}
                        <a href="{% url 'candidate:dashboard'%}"><img
                        src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
                        alt="User Avatar"
                        style="width: 36px;height: 36px;border-radius: 50%;object-fit: cover;"
                        class="avatar-circle"  ></a>
                    </div>
                    {% else %}
                    <div class="jobplugin__header-buttons">
                        <a href="{% url 'auth:login'%}" class="jobplugin__button button-white jobplugin__text-primary hover:jobplugin__bg-primary hover:jobplugin__text-white">Login</a>
                        <a href="{% url 'auth:signup'%}" class="jobplugin__button jobplugin__bg-primary hover:jobplugin__bg-secondary">Sign Up</a>
                    </div>
                    {% endif %}
                </div>
                <!-- Header Search Form Mobile Opener -->
                <button type="button" class="jobplugin__header-form__opener jobplugin__text-primary hover:jobplugin__text-white hover:jobplugin__bg-primary">
                    <span class="rj-icon rj-search"></span>
                </button>
                <!-- Main Navigation Mobile Opener -->
                <button type="button" class="jobplugin__navigation-opener">
                    <span class="jobplugin__bg-primary"></span>
                    <span class="jobplugin__bg-primary"></span>
                    <span class="jobplugin__bg-primary"></span>
                </button>
            </div>
        </div>
    </div>
</header>